export { Hero } from "./Hero";
export { ProductCategories } from "./ProductCategories";
export { WhyYanginPerde } from "./WhyYanginPerde";
export { TechnicalSpecs } from "./TechnicalSpecs";
export { HowItWorks } from "./HowItWorks";
export { Partners } from "./Partners";
export { References } from "./References";
export { SEOContent } from "./SEOContent";
export { CTASection } from "./CTASection";
